import {readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..');
const data=async(name,type)=>'data:'+type+';base64,'+(await readFile(root+'/public/'+name)).toString('base64');
let html=await readFile(root+'/dist/index.html','utf8');
const files=await readdir(root+'/dist/assets');
const js=await readFile(root+'/dist/assets/'+files.find(x=>/^index-.*\.js$/.test(x)),'utf8');
let css=await readFile(root+'/dist/assets/'+files.find(x=>/^index-.*\.css$/.test(x)),'utf8');
css=css.replace(/url\([^)]*geist\.woff2\)/g,`url("${await data('assets/geist.woff2','font/woff2')}")`);
html=html.replace(/<script type="module" crossorigin src="[^"]+"><\/script>/,'').replace(/<link rel="stylesheet" crossorigin href="[^"]+">/,()=>'<style>'+css+'</style>');
html=html.replace(/<link rel="preload"[^>]+>/,'');
const assets={};
for(const key of ['painel','producoes','caixa','bancada'])assets[key+'.webp']=await data('assets/'+key+'.webp','image/webp');
html=html.replaceAll('./assets/painel.webp',assets['painel.webp']).replaceAll('./assets/pl.svg',await data('assets/pl.svg','image/svg+xml')).replaceAll('./favicon.svg',await data('favicon.svg','image/svg+xml')).replaceAll('./assets/compartilhar.jpg',await data('assets/compartilhar.jpg','image/jpeg'));
html=html.replace('</body>',()=>'<script id="embedded-assets" type="application/json">'+JSON.stringify(assets)+'</script><script type="module">'+js.replaceAll('</script','<\\/script')+'</script></body>');
await writeFile(root+'/Project-Lab-Preview.html',html);
console.log('Preview HTML independente:',(Buffer.byteLength(html)/1024/1024).toFixed(2),'MB');
