export async function withPDFTimeout(promise, message, milliseconds = 30000) {
  let timer;
  try {
    return await Promise.race([
      promise,
      new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(message)), milliseconds); }),
    ]);
  } finally { clearTimeout(timer); }
}

export function pdfDocumentHTML(html) {
  if (!html.includes('<head>')) throw new Error('Documento de proposta inválido.');
  // WebKit stalls html2canvas's nested clone inside a sandboxed srcdoc frame.
  // Only use the escaped HTML generated by proposalDocument, never imported HTML.
  // CSP still disables scripts, plugins, connections, forms and base URL changes.
  return html.replace('<head>', `<head><meta http-equiv="Content-Security-Policy" content="script-src 'none'; object-src 'none'; connect-src 'none'; form-action 'none'; base-uri 'none'">`);
}

/** Capture the screen design, section by section, without invoking print CSS. */
export async function downloadProposalPDF(html, filename, onProgress = () => {}) {
  onProgress('Carregando gerador…');
  const [{ default: html2canvas }, { jsPDF }] = await withPDFTimeout(Promise.all([
    import('html2canvas'), import('jspdf'),
  ]), 'O gerador não carregou. Atualize a página e tente novamente.');
  const frame = document.createElement('iframe');
  frame.title = 'Preparação do PDF';
  frame.setAttribute('aria-hidden', 'true');
  frame.style.cssText = 'position:fixed;left:-12000px;top:0;width:1120px;height:900px;border:0;pointer-events:none;';
  try {
    const ready = new Promise(resolve => { frame.onload = resolve; });
    frame.srcdoc = pdfDocumentHTML(html);
    document.body.append(frame);
    onProgress('Preparando documento…');
    await withPDFTimeout(ready, 'A proposta demorou para carregar. Tente novamente.');
    const doc = frame.contentDocument;
    onProgress('Carregando fontes…');
    await withPDFTimeout(doc.fonts.ready, 'As fontes não carregaram. Tente novamente.');
    onProgress('Carregando imagens…');
    await withPDFTimeout(Promise.all([...doc.images].map(img => img.decode().catch(() => {
      throw new Error('Uma imagem da proposta não pôde ser lida. Substitua a imagem e tente novamente.');
    }))), 'As imagens demoraram para carregar. Tente novamente.');
    let pdf;
    const sections = [...(doc.querySelector('main')?.children || [])];
    for (const section of sections) {
      onProgress(`Gerando página ${sections.indexOf(section) + 1} de ${sections.length}…`);
      const canvas = await withPDFTimeout(html2canvas(section, {
        scale: 1.5, backgroundColor: '#f6f6f4', logging: false,
        windowWidth: 1120, windowHeight: 900,
      }), 'A geração desta página demorou demais. Tente novamente.');
      const width = 297;
      const height = Math.max(30, canvas.height / canvas.width * width);
      const orientation = height > width ? 'portrait' : 'landscape';
      if (!pdf) pdf = new jsPDF({ unit: 'mm', format: [width, height], orientation, compress: true });
      else pdf.addPage([width, height], orientation);
      pdf.addImage(canvas.toDataURL('image/jpeg', .95), 'JPEG', 0, 0, width, height);
      canvas.width = canvas.height = 0;
    }
    if (!pdf) throw new Error('A proposta está vazia.');
    onProgress('Baixando PDF…');
    pdf.setProperties({ title: filename, creator: 'Project Lab' });
    pdf.save(filename + '.pdf');
  } finally { frame.remove(); }
}
